version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_DATABASE=Informatik
      - DB_USERNAME=root
      - DB_PASSWORD=""
      - DB_HOST=db
      - DB_PORT=3306